name: Image Converter

on:
  pull_request_target:
    branches: [ "main" ]
  pull_request:
    paths: [ "image/input/before/**.png" ]

jobs:
  execute:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Python script - Image Converter
        run: |
          python image_convert.py

      - name: Check for modified files in Spotless
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push in Modified File
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git status
          git add .
          git commit -m "Image Converted."
          git push origin HEAD
